---
# tasks file for datab
- name: install mysql server
  apt: name={{ item }} state=installed
  with_items:
    - mysql-common
    - mysql-server
    - python-mysqldb
  tags:
    - mysql

- name: ensure mysql is running and starts on boot
  service: name=mysql state=started enabled=true
  tags:
    - mysql

- name: template .my.cnf to root folder
  template:
    src: .my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0400
  tags:
    - mysql
    - mysql_configure

- name: update mysql root password for all root accounts
  mysql_user:
    name: root
    host: localhost
    password: "{{ root_pass | mandatory }}"
  tags:
    - mysql
    - mysql_configure

- name: update mysql root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ root_pass | mandatory }}"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
  tags:
    - mysql
    - mysql_configure

- name: ensure anonymous users are not in the database
  mysql_user:
    name: ''
    host: "{{ item }}"
    state: absent
  with_items:
    - localhost
    - "{{ inventory_hostname }}"
  tags:
    - mysql
    - mysql_configure

- name: remove the test database
  mysql_db:
    name: test
    state: absent
  tags:
    - mysql
    - mysql_configure

- name: bind ip address
  template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
  tags:
    - mysql
    - mysql_configure

- name: Create WordPress database
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present
  tags:
    - wp_install
    - mysql

- name: Create the database users
  mysql_user:
    name: "{{ wp_db_name }}"
    password: "{{ wp_db_pass }}"
    host: "{{ wp_web_host }}"
    priv: "*.*:ALL"
  tags:
    - wp_install
    - mysql

- name: Copy Wordpress DB
  copy:
    src=wordpress3.sql
    dest=/tmp/wordpress3.sql
  tags:
    - wp_install

- name: Import Wordpress DB
  mysql_db:
    state: import
    name: "{{ wp_db_name }}"
    target: /tmp/wordpress3.sql
  ignore_errors: yes
  tags:
    - wp_install

- name: restart mysql
  service: name=mysql state=restarted
  tags:
    - wp_install
    - mysql
